baseURL: "/"
languageCode: "en"
title: "Basajan Starter"
author:
  name: "You"
  image: "https://i.pravatar.cc/256"
taxonomies:
  _merge: "deep"
minify:
  _merge: deep
module:
  imports:
    - path: github.com/hapakaien/hugo-themes/basajan
